export type Lang = 'ru' | 'he' | 'en'

export const content = {
  he: {
    ui: {
      locationLabel: 'חלוצי התעשייה 19, חיפה',
      aboutLabel: 'מי אנחנו',
      photosLabel: 'צילומים',
      galleryTitle: 'גלריה',
      seeAllPhotos: '← לכל התמונות',
      reviewsLabel: 'מה אומרים עלינו',
      reviewsTitle: 'ביקורות',
      whereWeAreLabel: 'איפה אנחנו',
      contactPageLink: 'לדף יצירת קשר',
      openInMaps: 'פתח במפות Google',
      navLabel: 'ניווט מהיר',
      contactLabel: 'פרטי קשר',
    },
    nav: {
      home: 'בית',
      menu: 'תפריט',
      events: 'אירועים',
      gallery: 'גלריה',
      contact: 'צור קשר',
    },
    hero: {
      headline: 'המסעדה הטובה ביותר בחיפה',
      subline: '40–350 אורחים · מוזיקה חיה · ו׳–ש׳ + שבת · מ-₪250 לאדם',
      ctaPrimary: 'WhatsApp',
      ctaSecondary: 'WhatsApp',
      urgency: 'תאריכי קיץ 2026 מתמלאים במהירות',
    },
    about: {
      title: 'אודות פנורמה סטייל',
      text: 'מסעדה רוסית ומזרח אירופאית ייחודית בחיפה, המשלבת מטבח אותנטי עם אווירה חגיגית. מקום מושלם לארוחות משפחתיות ואירועים מכל הסוגים — מחתונות ועד אירועי חברה. פתוחים בשבת, מקבלים עד 350 אורחים.',
      stat1Label: 'דירוג',
      stat1Value: '4.5/5',
      stat2Label: 'דירוג בחיפה',
      stat2Value: '#111 מתוך 1,850',
      stat3Label: 'קיבולת אורחים',
      stat3Value: '40–350',
    },
    menu: {
      title: 'התפריט שלנו',
      priceNote: 'המחירים אינם מצוינים — צרו קשר לפרטים',
      categories: [
        {
          name: 'מנות פתיחה',
          items: ['ברוסקטה', 'מולים', 'סושי'],
        },
        {
          name: 'מנות עיקריות — בשר',
          items: ['קבב', 'קוטלט קייב (Котлета Киевская)', 'נתח חזיר (Pork Knuckle)', 'שאשליק (Шашлык)', 'סטייק'],
        },
        {
          name: 'פירות ים',
          items: ['דגים', 'שרימפס', 'מולים'],
        },
        {
          name: 'מרקים',
          items: ['שורפה (Шурпа)', 'אוחה — מרק דגים (Уха)'],
        },
        {
          name: 'משקאות',
          items: ['קוקטייל הבית — פנורמה סטייל', 'יין', 'בירה', 'משקאות חריפים', 'משקאות קלים', 'קפה'],
        },
        {
          name: 'קינוחים',
          items: ['מגוון קינוחים (לפי תפריט יומי)'],
        },
      ],
    },
    events: {
      title: 'אירועים ואולמות',
      subtitle: 'המקום המושלם לכל אירוע — מחתונות ועד ימי הולדת',
      capacityLabel: 'קיבולת',
      capacity: '40–350 אורחים',
      priceLabel: 'מחיר',
      price: 'מ-₪250 לאדם',
      includes: [
        'מזון ומשקאות',
        'מוזיקה חיה',
        'רקדנים ואומנים',
        'מסכי LED',
        'במה',
        'אולם VIP',
        'חניה',
        'פתוח בשבת',
        'אפשר להביא אלכוהול',
      ],
      addons: [
        'צלם',
        'צלם וידאו',
        'DJ',
        'מנחה אירוע',
        'עיצוב ודקורציות',
      ],
      types: [
        'חתונות',
        'בר/בת מצווה',
        'ימי הולדת',
        'אירועי חברה',
        'ימי נישואין',
        'מסיבות פרטיות',
      ],
      ctaWhatsapp: 'שאלה בוואטסאפ',
      ctaPhone: 'התקשרו עכשיו',
    },
    contact: {
      title: 'צור קשר',
      address: 'חלוצי התעשייה 19, חיפה, ישראל',
      phone: '+972-50-646-1983',
      whatsapp: '+972-50-646-1983',
      hoursNote: 'ו׳–ש׳ מ-18:00 · שבת מ-12:00 · ימי חול — בהזמנה מראש',
      facebookLabel: 'עמוד פייסבוק',
    },
    packages: [
      {
        name: 'Essential',
        price: '₪250',
        perPerson: 'לאדם',
        highlight: false,
        tag: '',
        includes: ['מזון ומשקאות', 'מוזיקה חיה', 'מסכי LED', 'במה', 'חניה', 'פתוח בשבת'],
      },
      {
        name: 'Premium',
        price: '₪290',
        perPerson: 'לאדם',
        highlight: true,
        tag: 'הכי פופולרי',
        includes: ['כל מה שב-Essential', 'צלם', 'צלם וידאו', 'DJ'],
      },
    ],
    halls: [
      { name: 'אולם בנקטים', capacity: '40–350', key: 'banquet' },
      { name: 'אולם VIP', capacity: 'עד 70', key: 'vip' },
    ],
    faq: [
      { q: 'אפשר להביא אלכוהול?', a: 'כן, ניתן להביא אלכוהול בחינם ללא קורקז.' },
      { q: 'האם פתוחים בשבת?', a: 'כן, אנחנו פתוחים בשבת ובחגים.' },
      { q: 'כמה אורחים אפשר להזמין?', a: 'אנחנו מקבלים בין 40 ל-350 אורחים.' },
      { q: 'האם המסעדה כשרה?', a: 'לא, המסעדה אינה כשרה.' },
      { q: 'אפשר להביא DJ חיצוני?', a: 'כן, ניתן לתאם עם הנהלה.' },
      { q: 'האם ניתן לבקר לפני האירוע?', a: 'בהחלט — שלחו הודעה בוואטסאפ לתיאום ביקור.' },
    ],
    whyUs: {
      label: 'למה פנורמה סטייל?',
      title: 'המקום המושלם לאירוע שלכם',
      stats: [
        { value: 'מ-₪250', label: 'לאדם — זול יותר ממרבית האולמות בחיפה' },
        { value: '#111', label: 'מתוך 1,850 מסעדות בחיפה' },
        { value: '4.5★', label: '386 ביקורות מאומתות' },
      ],
      perks: [
        'פתוחים בשבת',
        'אפשר להביא אלכוהול — ללא קורקז',
        'מוזיקה חיה כלולה בחבילה',
        '40 עד 350 אורחים — הכי גמיש בחיפה',
        'חניה חינם',
      ],
    },
    footer: {
      rights: '© 2026 פנורמה סטייל. כל הזכויות שמורות.',
      tagline: 'מסעדה רוסית ואולם אירועים — חיפה',
    },
  },
  ru: {
    ui: {
      locationLabel: 'Халуцей ха-Тасия 19, Хайфа',
      aboutLabel: 'О нас',
      photosLabel: 'Фотографии',
      galleryTitle: 'Галерея',
      seeAllPhotos: 'Все фото →',
      reviewsLabel: 'Отзывы',
      reviewsTitle: 'Что о нас говорят',
      whereWeAreLabel: 'Как нас найти',
      contactPageLink: 'Страница контактов',
      openInMaps: 'Открыть в Google Maps',
      navLabel: 'Навигация',
      contactLabel: 'Контакты',
    },
    nav: {
      home: 'Главная',
      menu: 'Меню',
      events: 'Мероприятия',
      gallery: 'Галерея',
      contact: 'Контакты',
    },
    hero: {
      headline: 'Лучший ресторан Хайфы',
      subline: '40–350 гостей · живая музыка · Пт–Сб + Шаббат · от ₪250',
      ctaPrimary: 'WhatsApp',
      ctaSecondary: 'WhatsApp',
      urgency: 'Летние 2026 даты заполняются быстро',
    },
    about: {
      title: 'О Panorama Style',
      text: 'Уникальный русский и восточноевропейский ресторан в Хайфе, сочетающий аутентичную кухню с праздничной атмосферой. Идеальное место для семейных ужинов и мероприятий любого формата — от свадеб до корпоративов. Работаем в Шаббат, вмещаем до 350 гостей.',
      stat1Label: 'Рейтинг',
      stat1Value: '4.5/5',
      stat2Label: 'Место в Хайфе',
      stat2Value: '#111 из 1850',
      stat3Label: 'Вместимость',
      stat3Value: '40–350',
    },
    menu: {
      title: 'Наше меню',
      priceNote: 'Цены уточняйте при бронировании',
      categories: [
        {
          name: 'Закуски',
          items: ['Брускетта', 'Мидии', 'Суши'],
        },
        {
          name: 'Горячее — Мясо',
          items: ['Кебаб', 'Котлета Киевская', 'Рулька (Pork Knuckle)', 'Шашлык', 'Стейк'],
        },
        {
          name: 'Морепродукты',
          items: ['Рыба', 'Креветки', 'Мидии'],
        },
        {
          name: 'Супы',
          items: ['Шурпа', 'Уха'],
        },
        {
          name: 'Напитки',
          items: ['Фирменный коктейль Panorama Style', 'Вино', 'Пиво', 'Крепкие напитки', 'Безалкогольные напитки', 'Кофе'],
        },
        {
          name: 'Десерты',
          items: ['Ассорти десертов (по сезонному меню)'],
        },
      ],
    },
    events: {
      title: 'Мероприятия и банкетный зал',
      subtitle: 'Идеальное место для любого события — от свадьбы до дня рождения',
      capacityLabel: 'Вместимость',
      capacity: '40–350 гостей',
      priceLabel: 'Цена',
      price: 'от ₪250 с человека',
      includes: [
        'Еда и напитки',
        'Живая музыка',
        'Танцоры и артисты',
        'LED-экраны',
        'Сцена',
        'VIP-зал',
        'Парковка',
        'Работаем в Шаббат',
        'Можно принести свой алкоголь',
      ],
      addons: [
        'Фотограф',
        'Видеооператор',
        'DJ',
        'Ведущий',
        'Оформление и декор',
      ],
      types: [
        'Свадьбы',
        'Бар/Бат-мицвы',
        'Дни рождения',
        'Корпоративы',
        'Годовщины',
        'Частные вечеринки',
      ],
      ctaWhatsapp: 'Написать в WhatsApp',
      ctaPhone: 'Позвонить сейчас',
    },
    contact: {
      title: 'Контакты',
      address: 'Халуцей ха-Тасия 19, Хайфа, Израиль',
      phone: '+972-50-646-1983',
      whatsapp: '+972-50-646-1983',
      hoursNote: 'Пт–Сб с 18:00 · Шаббат с 12:00 · Будни — по предварительной записи',
      facebookLabel: 'Страница Facebook',
    },
    packages: [
      {
        name: 'Essential',
        price: '₪250',
        perPerson: 'с человека',
        highlight: false,
        tag: '',
        includes: ['Еда и напитки', 'Живая музыка', 'LED-экраны', 'Сцена', 'Парковка', 'Работаем в Шаббат'],
      },
      {
        name: 'Premium',
        price: '₪290',
        perPerson: 'с человека',
        highlight: true,
        tag: 'Самый популярный',
        includes: ['Всё из Essential', 'Фотограф', 'Видеооператор', 'DJ'],
      },
    ],
    halls: [
      { name: 'Банкетный зал', capacity: '40–350', key: 'banquet' },
      { name: 'VIP зал', capacity: 'до 70', key: 'vip' },
    ],
    faq: [
      { q: 'Можно ли принести свой алкоголь?', a: 'Да, corkage fee не взимается.' },
      { q: 'Работаете ли вы в Шаббат?', a: 'Да, мы работаем в Шаббат и праздники.' },
      { q: 'Сколько гостей можно пригласить?', a: 'Мы принимаем от 40 до 350 гостей.' },
      { q: 'Является ли ресторан кошерным?', a: 'Нет, ресторан не кошерный.' },
      { q: 'Можно ли привести своего DJ?', a: 'Да, по согласованию с администрацией.' },
      { q: 'Можно ли посетить зал заранее?', a: 'Конечно — напишите в WhatsApp для записи на осмотр.' },
    ],
    whyUs: {
      label: 'Почему Panorama Style?',
      title: 'Идеальное место для вашего мероприятия',
      stats: [
        { value: 'от ₪250', label: 'с человека — дешевле большинства залов Хайфы' },
        { value: '#111', label: 'из 1850 ресторанов Хайфы' },
        { value: '4.5★', label: '386 проверенных отзывов' },
      ],
      perks: [
        'Работаем в Шаббат',
        'Можно принести свой алкоголь — без corkage fee',
        'Живая музыка включена в пакет',
        'От 40 до 350 гостей — самый гибкий формат в Хайфе',
        'Бесплатная парковка',
      ],
    },
    footer: {
      rights: '© 2026 Panorama Style. Все права защищены.',
      tagline: 'Русский ресторан и банкетный зал — Хайфа',
    },
  },
  en: {
    ui: {
      locationLabel: 'Halutzei HaTa\'asiya 19, Haifa',
      aboutLabel: 'Who We Are',
      photosLabel: 'Photography',
      galleryTitle: 'Gallery',
      seeAllPhotos: 'All Photos →',
      reviewsLabel: 'Reviews',
      reviewsTitle: 'What Guests Say',
      whereWeAreLabel: 'Find Us',
      contactPageLink: 'Contact Page',
      openInMaps: 'Open in Google Maps',
      navLabel: 'Quick Links',
      contactLabel: 'Contact',
    },
    nav: {
      home: 'Home',
      menu: 'Menu',
      events: 'Events',
      gallery: 'Gallery',
      contact: 'Contact',
    },
    hero: {
      headline: "Haifa's Best Restaurant",
      subline: '40–350 guests · live entertainment · Fri–Sat + Shabbat · from ₪250',
      ctaPrimary: 'WhatsApp',
      ctaSecondary: 'WhatsApp',
      urgency: 'Summer 2026 dates filling fast',
    },
    about: {
      title: 'About Panorama Style',
      text: 'A unique Russian and Eastern European restaurant in Haifa, blending authentic cuisine with a festive atmosphere. The perfect venue for family dinners and events of any kind — from weddings to corporate nights. Open on Shabbat, accommodating up to 350 guests.',
      stat1Label: 'Rating',
      stat1Value: '4.5/5',
      stat2Label: 'Ranked in Haifa',
      stat2Value: '#111 of 1,850',
      stat3Label: 'Guest Capacity',
      stat3Value: '40–350',
    },
    menu: {
      title: 'Our Menu',
      priceNote: 'Prices available on request',
      categories: [
        {
          name: 'Starters',
          items: ['Bruschetta', 'Mussels', 'Sushi'],
        },
        {
          name: 'Mains — Meat',
          items: ['Kebab', 'Kiev Cutlet', 'Pork Knuckle', 'Shashlik', 'Steak'],
        },
        {
          name: 'Seafood',
          items: ['Fish', 'Prawns', 'Mussels'],
        },
        {
          name: 'Soups',
          items: ['Shurpa', 'Ukha (fish soup)'],
        },
        {
          name: 'Drinks',
          items: ['Panorama Style Signature Cocktail', 'Wine', 'Beer', 'Spirits', 'Soft Drinks', 'Coffee'],
        },
        {
          name: 'Desserts',
          items: ['Seasonal dessert selection'],
        },
      ],
    },
    events: {
      title: 'Events & Banquet Hall',
      subtitle: 'The perfect venue for any occasion — from weddings to birthdays',
      capacityLabel: 'Capacity',
      capacity: '40–350 guests',
      priceLabel: 'Price',
      price: 'from ₪250 per person',
      includes: [
        'Food & drinks',
        'Live music',
        'Dancers & performers',
        'LED screens',
        'Stage',
        'VIP hall',
        'Parking',
        'Open on Shabbat',
        'Bring your own alcohol',
      ],
      addons: [
        'Photographer',
        'Videographer',
        'DJ',
        'Event host / MC',
        'Decoration services',
      ],
      types: [
        'Weddings',
        'Bar/Bat Mitzvahs',
        'Birthdays',
        'Corporate events',
        'Anniversaries',
        'Private parties',
      ],
      ctaWhatsapp: 'Message on WhatsApp',
      ctaPhone: 'Call Now',
    },
    contact: {
      title: 'Contact Us',
      address: 'Halutzei HaTa\'asiya 19, Haifa, Israel',
      phone: '+972-50-646-1983',
      whatsapp: '+972-50-646-1983',
      hoursNote: 'Fri–Sat from 18:00 · Shabbat from 12:00 · Weekdays by advance booking',
      facebookLabel: 'Facebook Page',
    },
    packages: [
      {
        name: 'Essential',
        price: '₪250',
        perPerson: 'per person',
        highlight: false,
        tag: '',
        includes: ['Food & drinks', 'Live music', 'LED screens', 'Stage', 'Parking', 'Open on Shabbat'],
      },
      {
        name: 'Premium',
        price: '₪290',
        perPerson: 'per person',
        highlight: true,
        tag: 'Most Popular',
        includes: ['Everything in Essential', 'Photographer', 'Videographer', 'DJ'],
      },
    ],
    halls: [
      { name: 'Banquet Hall', capacity: '40–350', key: 'banquet' },
      { name: 'VIP Hall', capacity: 'up to 70', key: 'vip' },
    ],
    faq: [
      { q: 'Can we bring our own alcohol?', a: 'Yes — no corkage fee.' },
      { q: 'Is the venue open on Shabbat?', a: 'Yes, we operate on Shabbat and holidays.' },
      { q: 'How many guests can we invite?', a: 'We accommodate 40 to 350 guests.' },
      { q: 'Is the restaurant kosher?', a: 'No, the restaurant is not kosher.' },
      { q: 'Can we bring our own DJ?', a: 'Yes, by arrangement with the venue.' },
      { q: 'Can we visit the venue beforehand?', a: 'Absolutely — message us on WhatsApp to schedule a viewing.' },
    ],
    whyUs: {
      label: 'Why Panorama Style?',
      title: 'The Ideal Venue for Your Event',
      stats: [
        { value: 'from ₪250', label: 'per person — more affordable than most halls in Haifa' },
        { value: '#111', label: 'of 1,850 restaurants in Haifa' },
        { value: '4.5★', label: '386 verified reviews' },
      ],
      perks: [
        'Open on Shabbat',
        'Bring your own alcohol — no corkage fee',
        'Live entertainment included',
        '40–350 guests — most flexible range in Haifa',
        'Free parking',
      ],
    },
    footer: {
      rights: '© 2026 Panorama Style. All rights reserved.',
      tagline: 'Russian Restaurant & Event Hall — Haifa',
    },
  },
}
