export type Lang = 'ru' | 'he' | 'en'

export const content = {
  he: {
    ui: {
      locationLabel: 'חיפה, ישראל',
      aboutLabel: 'מי אנחנו',
      photosLabel: 'צילומים',
      galleryTitle: 'גלריה',
      seeAllPhotos: 'לכל התמונות →',
      reviewsLabel: 'מה אומרים עלינו',
      reviewsTitle: 'ביקורות',
      whereWeAreLabel: 'איפה אנחנו',
      contactPageLink: 'לדף יצירת קשר',
      openInMaps: 'פתח במפות Google',
      navLabel: 'ניווט מהיר',
      contactLabel: 'פרטי קשר',
    },
    nav: {
      home: 'בית',
      menu: 'תפריט',
      events: 'אירועים',
      gallery: 'גלריה',
      contact: 'צור קשר',
    },
    hero: {
      headline: 'פנורמה סטייל',
      subline: 'מסעדה רוסית ואולם אירועים בחיפה — חוויה קולינרית בלתי נשכחת',
      ctaPrimary: 'לפרטי אירועים',
      ctaSecondary: 'צור קשר',
    },
    about: {
      title: 'אודות פנורמה סטייל',
      text: 'מסעדה רוסית ומזרח אירופאית ייחודית בחיפה, המשלבת מטבח אותנטי עם אווירה חגיגית. מקום מושלם לארוחות משפחתיות ואירועים מכל הסוגים — מחתונות ועד אירועי חברה. פתוחים בשבת, מקבלים עד 350 אורחים.',
      stat1Label: 'דירוג',
      stat1Value: '4.2/5',
      stat2Label: 'דירוג בחיפה',
      stat2Value: '#111 מתוך 1,850',
      stat3Label: 'קיבולת אורחים',
      stat3Value: '40–350',
    },
    menu: {
      title: 'התפריט שלנו',
      priceNote: 'המחירים אינם מצוינים — צרו קשר לפרטים',
      categories: [
        {
          name: 'מנות פתיחה',
          items: ['ברוסקטה', 'מולים', 'סושי'],
        },
        {
          name: 'מנות עיקריות — בשר',
          items: ['קבב', 'קוטלט קייב (Котлета Киевская)', 'נתח חזיר (Pork Knuckle)', 'שאשליק (Шашлык)', 'סטייק'],
        },
        {
          name: 'פירות ים',
          items: ['דגים', 'שרימפס', 'מולים'],
        },
        {
          name: 'מרקים',
          items: ['שורפה (Шурпа)', 'אוחה — מרק דגים (Уха)'],
        },
        {
          name: 'משקאות',
          items: ['קוקטייל הבית — פנורמה סטייל', 'יין', 'בירה', 'משקאות חריפים', 'משקאות קלים', 'קפה'],
        },
        {
          name: 'קינוחים',
          items: ['מגוון קינוחים (לפי תפריט יומי)'],
        },
      ],
    },
    events: {
      title: 'אירועים ואולמות',
      subtitle: 'המקום המושלם לכל אירוע — מחתונות ועד ימי הולדת',
      capacityLabel: 'קיבולת',
      capacity: '40–350 אורחים',
      priceLabel: 'מחיר',
      price: 'מ-₪250 לאדם',
      includes: [
        'מזון ומשקאות',
        'מוזיקה חיה',
        'רקדנים ואומנים',
        'מסכי LED',
        'במה',
        'אולם VIP',
        'חניה',
        'פתוח בשבת',
        'אפשר להביא אלכוהול',
      ],
      addons: [
        'צלם',
        'צלם וידאו',
        'DJ',
        'מנחה אירוע',
        'עיצוב ודקורציות',
      ],
      types: [
        'חתונות',
        'בר/בת מצווה',
        'ימי הולדת',
        'אירועי חברה',
        'ימי נישואין',
        'מסיבות פרטיות',
      ],
      ctaWhatsapp: 'שאלה בוואטסאפ',
      ctaPhone: 'התקשרו עכשיו',
    },
    contact: {
      title: 'צור קשר',
      address: 'חלוצי התעשייה 19, חיפה, ישראל',
      phone: '+972-50-800-5606',
      whatsapp: '+972-50-646-1983',
      hoursNote: 'לשאלות שעות ופרטים — צרו קשר ישירות',
      facebookLabel: 'עמוד פייסבוק',
    },
    footer: {
      rights: '© 2026 פנורמה סטייל. כל הזכויות שמורות.',
      tagline: 'מסעדה רוסית ואולם אירועים — חיפה',
    },
  },
  ru: {
    ui: {
      locationLabel: 'Хайфа, Израиль',
      aboutLabel: 'О нас',
      photosLabel: 'Фотографии',
      galleryTitle: 'Галерея',
      seeAllPhotos: 'Все фото →',
      reviewsLabel: 'Отзывы',
      reviewsTitle: 'Что о нас говорят',
      whereWeAreLabel: 'Как нас найти',
      contactPageLink: 'Страница контактов',
      openInMaps: 'Открыть в Google Maps',
      navLabel: 'Навигация',
      contactLabel: 'Контакты',
    },
    nav: {
      home: 'Главная',
      menu: 'Меню',
      events: 'Мероприятия',
      gallery: 'Галерея',
      contact: 'Контакты',
    },
    hero: {
      headline: 'Panorama Style',
      subline: 'Русский ресторан и банкетный зал в Хайфе — незабываемый кулинарный опыт',
      ctaPrimary: 'Заказать мероприятие',
      ctaSecondary: 'Связаться с нами',
    },
    about: {
      title: 'О Panorama Style',
      text: 'Уникальный русский и восточноевропейский ресторан в Хайфе, сочетающий аутентичную кухню с праздничной атмосферой. Идеальное место для семейных ужинов и мероприятий любого формата — от свадеб до корпоративов. Работаем в Шаббат, вмещаем до 350 гостей.',
      stat1Label: 'Рейтинг',
      stat1Value: '4.2/5',
      stat2Label: 'Место в Хайфе',
      stat2Value: '#111 из 1850',
      stat3Label: 'Вместимость',
      stat3Value: '40–350',
    },
    menu: {
      title: 'Наше меню',
      priceNote: 'Цены уточняйте при бронировании',
      categories: [
        {
          name: 'Закуски',
          items: ['Брускетта', 'Мидии', 'Суши'],
        },
        {
          name: 'Горячее — Мясо',
          items: ['Кебаб', 'Котлета Киевская', 'Рулька (Pork Knuckle)', 'Шашлык', 'Стейк'],
        },
        {
          name: 'Морепродукты',
          items: ['Рыба', 'Креветки', 'Мидии'],
        },
        {
          name: 'Супы',
          items: ['Шурпа', 'Уха'],
        },
        {
          name: 'Напитки',
          items: ['Фирменный коктейль Panorama Style', 'Вино', 'Пиво', 'Крепкие напитки', 'Безалкогольные напитки', 'Кофе'],
        },
        {
          name: 'Десерты',
          items: ['Ассорти десертов (по сезонному меню)'],
        },
      ],
    },
    events: {
      title: 'Мероприятия и банкетный зал',
      subtitle: 'Идеальное место для любого события — от свадьбы до дня рождения',
      capacityLabel: 'Вместимость',
      capacity: '40–350 гостей',
      priceLabel: 'Цена',
      price: 'от ₪250 с человека',
      includes: [
        'Еда и напитки',
        'Живая музыка',
        'Танцоры и артисты',
        'LED-экраны',
        'Сцена',
        'VIP-зал',
        'Парковка',
        'Работаем в Шаббат',
        'Можно принести свой алкоголь',
      ],
      addons: [
        'Фотограф',
        'Видеооператор',
        'DJ',
        'Ведущий',
        'Оформление и декор',
      ],
      types: [
        'Свадьбы',
        'Бар/Бат-мицвы',
        'Дни рождения',
        'Корпоративы',
        'Годовщины',
        'Частные вечеринки',
      ],
      ctaWhatsapp: 'Написать в WhatsApp',
      ctaPhone: 'Позвонить сейчас',
    },
    contact: {
      title: 'Контакты',
      address: 'Халуцей ха-Тасия 19, Хайфа, Израиль',
      phone: '+972-50-800-5606',
      whatsapp: '+972-50-646-1983',
      hoursNote: 'Для уточнения часов работы — свяжитесь с нами напрямую',
      facebookLabel: 'Страница Facebook',
    },
    footer: {
      rights: '© 2026 Panorama Style. Все права защищены.',
      tagline: 'Русский ресторан и банкетный зал — Хайфа',
    },
  },
  en: {
    ui: {
      locationLabel: 'Haifa, Israel',
      aboutLabel: 'Who We Are',
      photosLabel: 'Photography',
      galleryTitle: 'Gallery',
      seeAllPhotos: 'All Photos →',
      reviewsLabel: 'Reviews',
      reviewsTitle: 'What Guests Say',
      whereWeAreLabel: 'Find Us',
      contactPageLink: 'Contact Page',
      openInMaps: 'Open in Google Maps',
      navLabel: 'Quick Links',
      contactLabel: 'Contact',
    },
    nav: {
      home: 'Home',
      menu: 'Menu',
      events: 'Events',
      gallery: 'Gallery',
      contact: 'Contact',
    },
    hero: {
      headline: 'Panorama Style',
      subline: 'Russian restaurant and event hall in Haifa — an unforgettable culinary experience',
      ctaPrimary: 'Book an Event',
      ctaSecondary: 'Get in Touch',
    },
    about: {
      title: 'About Panorama Style',
      text: 'A unique Russian and Eastern European restaurant in Haifa, blending authentic cuisine with a festive atmosphere. The perfect venue for family dinners and events of any kind — from weddings to corporate nights. Open on Shabbat, accommodating up to 350 guests.',
      stat1Label: 'Rating',
      stat1Value: '4.2/5',
      stat2Label: 'Ranked in Haifa',
      stat2Value: '#111 of 1,850',
      stat3Label: 'Guest Capacity',
      stat3Value: '40–350',
    },
    menu: {
      title: 'Our Menu',
      priceNote: 'Prices available on request',
      categories: [
        {
          name: 'Starters',
          items: ['Bruschetta', 'Mussels', 'Sushi'],
        },
        {
          name: 'Mains — Meat',
          items: ['Kebab', 'Kiev Cutlet', 'Pork Knuckle', 'Shashlik', 'Steak'],
        },
        {
          name: 'Seafood',
          items: ['Fish', 'Prawns', 'Mussels'],
        },
        {
          name: 'Soups',
          items: ['Shurpa', 'Ukha (fish soup)'],
        },
        {
          name: 'Drinks',
          items: ['Panorama Style Signature Cocktail', 'Wine', 'Beer', 'Spirits', 'Soft Drinks', 'Coffee'],
        },
        {
          name: 'Desserts',
          items: ['Seasonal dessert selection'],
        },
      ],
    },
    events: {
      title: 'Events & Banquet Hall',
      subtitle: 'The perfect venue for any occasion — from weddings to birthdays',
      capacityLabel: 'Capacity',
      capacity: '40–350 guests',
      priceLabel: 'Price',
      price: 'from ₪250 per person',
      includes: [
        'Food & drinks',
        'Live music',
        'Dancers & performers',
        'LED screens',
        'Stage',
        'VIP hall',
        'Parking',
        'Open on Shabbat',
        'Bring your own alcohol',
      ],
      addons: [
        'Photographer',
        'Videographer',
        'DJ',
        'Event host / MC',
        'Decoration services',
      ],
      types: [
        'Weddings',
        'Bar/Bat Mitzvahs',
        'Birthdays',
        'Corporate events',
        'Anniversaries',
        'Private parties',
      ],
      ctaWhatsapp: 'Message on WhatsApp',
      ctaPhone: 'Call Now',
    },
    contact: {
      title: 'Contact Us',
      address: 'Halutzei HaTa\'asiya 19, Haifa, Israel',
      phone: '+972-50-800-5606',
      whatsapp: '+972-50-646-1983',
      hoursNote: 'Contact us directly for opening hours and details',
      facebookLabel: 'Facebook Page',
    },
    footer: {
      rights: '© 2026 Panorama Style. All rights reserved.',
      tagline: 'Russian Restaurant & Event Hall — Haifa',
    },
  },
}
